# Generated by Django 4.2.6 on 2023-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='reg_id',
            new_name='child_id',
        ),
    ]
