# Generated by Django 4.2.6 on 2023-10-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_reg_id_child_child_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='address',
        ),
        migrations.RemoveField(
            model_name='child',
            name='phone',
        ),
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
