# Generated by Django 4.2.6 on 2023-10-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_child_address_remove_child_phone_child_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='video/')),
                ('upload_name', models.CharField(max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent')),
            ],
        ),
    ]
