# Generated by Django 4.2.6 on 2023-10-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('books_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_book', models.FileField(blank=True, null=True, upload_to='book/')),
                ('upload_name', models.CharField(max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent')),
            ],
        ),
        migrations.CreateModel(
            name='kids_video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_videos', models.FileField(blank=True, null=True, upload_to='video/')),
                ('upload_name', models.CharField(max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('vid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent')),
            ],
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
