# Generated by Django 4.2.6 on 2023-10-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_books_kids_video_delete_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='lib_id',
            new_name='parent_id',
        ),
        migrations.RenameField(
            model_name='kids_video',
            old_name='vid_id',
            new_name='parent_id',
        ),
    ]
