# Generated by Django 4.2.6 on 2023-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_lib_id_books_parent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids_video',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
