# Generated by Django 4.2.6 on 2023-11-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_kids_video_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='kids_game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_game', models.FileField(blank=True, null=True, upload_to='img/')),
                ('upload_name', models.CharField(max_length=100)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent')),
            ],
        ),
    ]
