# Generated by Django 4.2.6 on 2023-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_kids_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
