# Generated by Django 4.2.6 on 2023-11-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_category',
            fields=[
                ('book_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='video_category',
            fields=[
                ('video_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
