# Generated by Django 4.2.6 on 2023-11-16 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_book_category_video_category_books_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.book_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kids_video',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.video_category'),
            preserve_default=False,
        ),
    ]
