from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('home/<int:uid>/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('approve_parent/<int:uid>/', views.approve_parent_list, name='approve_parent'),
    path('parent_reg/', views.parent_regi, name='parent_reg'),
    path('admin_act/<int:uid>/', views.admin_act, name='admin_act'),
    path('logout/', views.logout, name='logout'),
    path('parent_home/<int:uid>/', views.parent_home, name='parent_home'),
    path('child_home/<int:uid>/', views.child_home, name='child_home'),
    path('delete_user/<int:uid>/<int:id>/', views.delete_user, name='delete_user'),
    path('approve/<int:uid>/<int:id>/', views.approve, name='approve'),
    path('reject/<int:uid>/<int:id>/', views.reject, name='reject'),
    path('child_reg/<int:uid>/', views.child_reg, name='child_reg'),
    path('videos/<int:uid>/',views.kids_videos, name='videos'),
    path('video_display/<int:uid>/',views.video_display, name='video_display'),
    path('books/<int:uid>/', views.kids_book, name='books'),
    path('book_display/<int:uid>/', views.book_display, name='book_display'),
    path('uploads_approve/<int:uid>/', views.uploads_approve, name='uploads_approve'),
    path('parent_edit/<int:uid>/', views.edit, name='parent_edit'),
    path('parent_view/<int:uid>/', views.parent_view, name='parent_view'),
    path('child_list/<int:uid>/', views.child_list, name='child_list'),
    path('child_edit/<int:uid>/', views.child_edit, name='child_edit'),
    path('video_approve/<int:uid>/<int:id>/', views.video_approve, name='video_approve'),
    path('video_reject/<int:uid>/<int:id>/', views.video_reject, name='video_reject'),
    path('games/<int:uid>/', views.games, name='games'),
    path('parent_video_display/<int:uid>/', views.parent_video_display, name='parent_video_display'),
    path('parent_book_display/<int:uid>/', views.parent_book_display, name='parent_book_display'),
    path('kids_game/<int:uid>/', views.kids_game, name='kids_game'),
    path('uploads_edit/<int:uid>/', views.uploads_edit, name='uploads_edit'),
    path('delete/<int:uid>/<int:id>/', views.delete, name='delete'),
    path('book_delete/<int:uid>/<int:id>/', views.book_delete, name='book_delete'),
    path('add_video_category/<int:uid>/', views.add_video_category, name='add_video_category'),
    path('video_edit_category/<int:uid>/', views.video_edit_category, name='video_edit_category'),
    path('video_catogery_list/<int:uid>/', views.video_catogery_list, name='video_catogery_list'),
    path('video_delete_category/<int:uid>/', views.video_delete_category, name='video_delete_category'),
    path('add_book_category/<int:uid>/', views.add_book_category, name='add_book_category'),
    path('book_edit_category/<int:uid>/<int:id>/', views.book_edit_category, name='book_edit_category'),
    path('book_category_list/<int:uid>/', views.book_category_list, name='book_category_list'),
    path('book_delete_category/<int:uid>/', views.book_delete_category, name='book_delete_category'),
    # path('add_new_child/<int:uid>/', views.add_new_child, name='add_new_child'),
]

